### ISSUE TITLE
Error when inserting string with question marks

### ISSUE THREAD

**Issue by dekelev** [felixmosh/knex-on-duplicate-update#2]
When trying to insert a string with question marks to a column and using `onDuplicateUpdate` method, an error is thrown on mismatch between expected bindings and actual values: `Error: Expected 2 bindings, saw 0`

The regex in the following line from raw.js (in knex module) file is matching against `??` in the whole query instead of only after the `on duplicate key update ` part:

`const sql = raw.sql.replace(/\\?\?\??/g, function (match) {`

**Comment by dekelev** [comment]
Closing this as the bug is part of the `knex` module:
https://github.com/tgriesser/knex/issues/3304

**Comment by tavolate** [comment]
Hello,

I still have the issue with knex v0.19.4 and knen-on-duplicate-update v1.1.1.

Below the details of the error:

`
{ method: 'raw',
  sql:
   'insert into `V` (`CODICE`, `DESCRIZIONE`) values (\'V0062924\', \'http://dsdsd.ds/rer\\?fd=3\\r\\n\') on duplicate key update `CODICE`=?, `DESCRIZIONE`=?',
  bindings: [ 'V0062924', 'http://dsdsd.ds/rer?fd=3\r\n' ],
  options: {},
  __knexQueryUid: '113b33a7-7653-4d6b-b7bb-138f376adfe3' }
{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fd=3\r\n') on duplicate key update `CODICE`='http://dsdsd.ds/rer?fd=3\r\n', `DES' at line 1
    at Query.Sequence._packetToError (/private/tmp/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/private/tmp/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/private/tmp/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/private/tmp/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/private/tmp/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/private/tmp/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/private/tmp/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/private/tmp/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/private/tmp/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/private/tmp/node_modules/mysql/lib/Connection.js:201:25)
    at /private/tmp/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/private/tmp/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/private/tmp/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/private/tmp/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/private/tmp/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/private/tmp/node_modules/knex/lib/client.js:158:17)
    at /private/tmp/node_modules/knex/lib/transaction.js:325:24
    at Promise._execute (/private/tmp/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/private/tmp/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/private/tmp/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.trxClient.query (/private/tmp/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query (/private/tmp/node_modules/knex/lib/runner.js:135:36)
    at /private/tmp/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/private/tmp/node_modules/bluebird/js/release/util.js:16:23)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'fd=3\\r\\n\') on duplicate key update `CODICE`=\'http://dsdsd.ds/rer?fd=3\\r\\n\', `DES\' at line 1',
  sqlState: '42000',
  index: 0,
  sql:
   'insert into `V` (`CODICE`, `DESCRIZIONE`) values (\'V0062924\', \'http://dsdsd.ds/rer\\\'V0062924\'fd=3\\r\\n\') on duplicate key update `CODICE`=\'http://dsdsd.ds/rer?fd=3\\r\\n\', `DESCRIZIONE`=?' }
Error: Error: insert into `V` (`CODICE`, `DESCRIZIONE`) values ('V0062924', 'http://dsdsd.ds/rer?fd=3\r\n') on duplicate key update `CODICE`='V0062924', `DESCRIZIONE`='http://dsdsd.ds/rer?fd=3\r\n' - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fd=3\r\n') on duplicate key update `CODICE`='http://dsdsd.ds/rer?fd=3\r\n', `DES' at line 1`

As you can see, the parameter is replaced inside the address url
