### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined after upgrading to 1.1.3

### ISSUE THREAD

**Issue by hercegnovi** [felixmosh/knex-on-duplicate-update#9]
Hi, when upgrading from 1.1.2 to 1.1.3 I get the following error. Any recommendations? 

Knex.QueryBuilder.extend('onDuplicateUpdate', function onDuplicateUpdate(...columns) {
[0]                     ^
[0]
[0] TypeError: Cannot read property 'extend' of undefined
[0]     at attachOnDuplicateUpdate (node_modules/knex-on-duplicate-update/lib/index.js:4:21)
[0]     at Object.<anonymous> (routes/hotels.js:21:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:1200:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1049:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
[0]     at Module.require (internal/modules/cjs/loader.js:1089:19)
[0]     at require (internal/modules/cjs/helpers.js:73:18)
[0]     at Object.<anonymous> (/server.js:90:20)
[0]     at Module._compile (internal/modules/cjs/loader.js:1200:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1049:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[0]     at internal/main/run_main_module.js:17:47

**Comment by felixmosh** [comment]
Hi, sorry for the late response, for some reason I don’t get notifications.

´extend´ is the official api of Knex which allows to extend the query builder.
You need to update your knex version (at least to 0.19.1)
